####################################
# BletchMAME Windows Github Action #
####################################

name: Windows

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:

    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install MSYS2
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        release: false
        install: git parallel p7zip mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-polly

    # Cache Dependencies
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v2
      env:
        cache-name: cache-deps
      with:
        path: ~/deps/msys2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('scripts/*_build_msys2.sh', 'scripts/*_retrieve.sh')}}

    # Make space for dependency builds
    - name: Make space for dependency builds
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        ls -l "/c"
        ls -l "/c/Program Files"        
        ls -l "/c/Program Files (x86)"

    # Build Qt6
    - name: Build Qt6
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        sh scripts/qt6_retrieve.sh
        sh scripts/qt6_build_msys2.sh

    # Build QuaZip
    - name: Build QuaZip
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        sh scripts/quazip_retrieve.sh
        sh scripts/quazip_build_msys2.sh

    # Build BletchMAME
    - name: Build BletchMAME
      run: |
        sh scripts/bletchmame_build_msys2.sh

    # Run Unit Tests
    - name: Run Unit Tests
      run: ./build/msys2/BletchMAME_tests.exe

    # Run integration testing with actual MAME
    - name: Run integration testing with actual MAME
      run: |
        mkdir -p deps/roms
        curl -L "https://www.mamedev.org/roms/alienar/alienar.zip" > deps/roms/alienar.zip
        cat | parallel "./test_mame_interactions.sh" <<- EOF
            mame0213
            mame0218
            mame0224
            mame0226
            mame0227
            mame0229
        EOF

    # Install PanDoc
    - name: Install PanDoc
      shell: bash
      run: |
        test -d deps || mkdir deps
        curl -L -f "https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-windows-x86_64.zip" > deps/pandoc-2.10.1-windows-x86_64.zip
        7z x deps/pandoc-2.10.1-windows-x86_64.zip -odeps

    # Generate readme.html
    - name: Generate readme.html
      run: deps/pandoc-2.10.1/pandoc.exe README.md -o readme.html

    # Build MSI - Candle
    - name: Build MSI - Candle
      run: /c/program\ files\ \(x86\)/WiX\ Toolset\ v3.11/bin/candle -v bletchmame.wxs -dVERSION=`cat buildversion.txt` -dQTBIN=./deps/Qt/5.15.1/mingw81_64/bin -out bletchmame.wixobj
        
    # Build MSI - Light
    - name: Build MSI - Light
      run: /c/program\ files\ \(x86\)/WiX\ Toolset\ v3.11/bin/light -v -ext WixUIExtension -ext WixUtilExtension bletchmame.wixobj -out BletchMAME.msi
        
    # Prepare Artifacts
    - name: Prepare Artifacts
      shell: bash
      run: |
        mkdir rel
        cp buildversion.txt rel/version_latest.txt
        mv BletchMAME.msi rel/BletchMAME_latest.msi
        7z a rel/BletchMAME_latest.zip BletchMAME.exe
        7z a rel/BletchMAME_latest.zip readme.html
        7z a rel/BletchMAME_latest.zip plugins

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      if: success() && github.ref == 'refs/heads/master'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      
    # Deploy Artifacts to S3
    - name: Deploy Artifacts to S3
      if: success() && github.ref == 'refs/heads/master'
      shell: bash
      run: aws s3 sync ./rel/ s3://bletchmame/files/ --delete
