##########################################
# BletchMAME Windows MSYS2 Github Action #
##########################################

name: Windows MSYS2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        qt: [6.1.2, 6.2.0]
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:

    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install MSYS2
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        release: false
        install: git parallel p7zip mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-polly mingw-w64-x86_64-mlir mingw-w64-x86_64-clang mingw-w64-x86_64-clang-analyzer mingw-w64-x86_64-clang-tools-extra patch

    # Cache Dependencies
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v2
      env:
        cache-name: cache-deps
      with:
        path: deps/msys2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.build_type }}-${{ matrix.qt }}-${{ hashFiles('.github/workflows/windows_msys2.yml', 'scripts/qt6_retrieve.sh', 'scripts/qt6_build_msys2.sh', 'scripts/quazip_build_msys2.sh')}}

    # Set Up Junction To C Drive
    - name: Set Up Junction To C Drive
      if: steps.cache-deps.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        mkdir C:\deps-qt6
        mklink /J deps/qt6 C:\deps-qt6
        mkdir C:\deps-msys2
        mklink /J deps/msys2 C:\deps-msys2

    # Install old CMake (needed for Qt6 build)
    - name: Install old CMake (needed for Qt6 build)
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        pacman -U --noconfirm http://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-cmake-3.21.3-1-any.pkg.tar.zst

    # Retrieve Qt6
    - name: Retrieve Qt6
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        sh scripts/qt6_retrieve.sh -q ${{ matrix.qt }}

    # Retrieve QuaZip
    - name: Retrieve QuaZip
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        git submodule update deps/quazip

    # Build Qt6
    - name: Build Qt6
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        sh scripts/qt6_build_msys2.sh

    # Build QuaZip
    - name: Build QuaZip
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        sh scripts/quazip_build_msys2.sh

    # Build BletchMAME
    - name: Build BletchMAME
      run: |
        sh scripts/bletchmame_build_msys2.sh -b ${{ matrix.build_type }}

    # Validate DLL Imports
    - name: Validate DLL Imports
      run: perl scripts/validate_dllimports.pl

    # Run Unit Tests
    - name: Run Unit Tests
      shell: bash
      run: |
        ./build/msys2/BletchMAME_tests.exe

    # Run integration testing with actual MAME
    - name: Run integration testing with actual MAME
      run: |
        sh scripts/run_mame_integration_testing.sh

    # Install PanDoc
    - name: Install PanDoc
      shell: bash
      run: |
        mkdir -p deps
        curl -L -f "https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-windows-x86_64.zip" > deps/pandoc-2.10.1-windows-x86_64.zip
        7z x deps/pandoc-2.10.1-windows-x86_64.zip -odeps

    # Generate readme.html
    - name: Generate readme.html
      run: deps/pandoc-2.10.1/pandoc.exe README.md -o readme.html

    # Build MSI - Candle
    - name: Build MSI - Candle
      run: /c/program\ files\ \(x86\)/WiX\ Toolset\ v3.11/bin/candle -v bletchmame.wxs -dVERSION=`git describe --tags | perl scripts/process_version.pl` -out bletchmame.wixobj
        
    # Build MSI - Light
    - name: Build MSI - Light
      run: /c/program\ files\ \(x86\)/WiX\ Toolset\ v3.11/bin/light -v -ext WixUIExtension -ext WixUtilExtension bletchmame.wixobj -out BletchMAME.msi
        
    # Prepare Artifacts
    - name: Prepare Artifacts
      shell: bash
      run: |
        mkdir rel
        git describe --tags | perl scripts/process_version.pl > rel/version_latest.txt
        mv BletchMAME.msi rel/BletchMAME_latest.msi
        7z a rel/BletchMAME_latest.zip ./build/msys2/bin/BletchMAME.exe
        7z a rel/BletchMAME_latest.zip readme.html
        7z a rel/BletchMAME_latest.zip plugins

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      if: success() && github.ref == 'refs/heads/master' && matrix.build_type == 'Release' && matrix.qt == '6.1.2'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      
    # Deploy Artifacts to S3
    - name: Deploy Artifacts to S3
      if: success() && github.ref == 'refs/heads/master' && matrix.build_type == 'Release' && matrix.qt == '6.1.2'
      shell: bash
      run: aws s3 sync ./rel/ s3://bletchmame/files/ --delete
